# Generated by Django 3.2.5 on 2022-09-01 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='residences',
            new_name='Residences',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='User',
        ),
    ]
