# Generated by Django 3.2.5 on 2022-08-26 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
