# Generated by Django 3.2.5 on 2022-09-01 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilityType', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('payDate', models.DateField()),
                ('accountNumber', models.IntegerField()),
                ('accountUsername', models.CharField(max_length=20)),
                ('accountPassword', models.CharField(max_length=20)),
                ('primaryContact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=255)),
                ('nickName', models.CharField(default='', max_length=255)),
                ('rent', models.IntegerField()),
                ('utilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.utility')),
            ],
        ),
    ]
