# Generated by Django 3.2.5 on 2022-08-26 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residence',
            name='isLivingAt',
        ),
    ]
