# Generated by Django 3.2.5 on 2022-09-08 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0003_auto_20220908_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='utilities',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='residence.utility'),
        ),
    ]
