# Generated by Django 3.2.5 on 2022-09-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0005_alter_residence_utilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='rent',
            field=models.IntegerField(null=True),
        ),
    ]
