# Generated by Django 3.2.5 on 2022-09-08 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residence', '0006_alter_residence_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='canView',
            field=models.ManyToManyField(related_name='viewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
