# Generated by Django 3.2.5 on 2022-09-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0007_residence_canview'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
    ]
