# Generated by Django 3.2.5 on 2022-09-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, default='rather_not_say', max_length=255, null=True),
        ),
    ]
